### ISSUE TITLE
微信小程序demo合流黑屏 是什么原因？

### ISSUE THREAD

**Issue by Lich3nbo** [pili-engineering/QNRTC-WxApp#21]
步骤
1.用户的roomToken是我在控制台生成
2.小程序中 app.js => appid 已改成应用id
3.room => index.js  
createMergeJob对象   
createMergeJob: {
      id: 'test',
      width: 720,
      height: 1280,
      stretchMode: 'aspectFill',
      publishUrl: '已替换我们自己直播流',
      subscribeUrl: 'rtmp://123.59.184.113:1935/jztest11/merge_test_job?domain=pili-live-rtmp.jztest11.test.cloudvdn.com'
    },

步骤是这样的 其他地方没有改变，
创建流用的也是小程序创建流的方式， 
直播流在后台的活跃流中显示    但播放后是黑屏

**Comment by yydounai1234** [comment]
创建完合流后，需要添加合流中的音视频轨。
可以看下这个文档：https://doc.qnsdk.com/rtn/wxapp/docs/api.html#1_0_8
