### ISSUE TITLE
live-player 和 live-pusher同层渲染

### ISSUE THREAD

**Issue by xudongjian** [pili-engineering/QNRTC-WxApp#6]
live-player 和 live-pusher同层渲染有问题，怎么实现双人嵌套界面聊天

**Comment by disoul** [comment]
这个小程序本身限制，目前无法实现。
可以考虑修改一下 UI

**Comment by disoul** [comment]
https://developers.weixin.qq.com/community/develop/doc/00046cc5a3095064a8479e30756400?highLine=live
可以参考这里的做法
